output_fields:
  - Discovery Range
  - Network IP
  - Network mask (or bits)
  - Location

global_rules:
  - ignore_cidr_less_than: 16

templates:
  T1:
    name: DC1 SolarWinds
    file_pattern: dc1-dc1solwind-*.xlsx
    mappings:
      Discovery Range: 
        - prefix: dc1_
        - column: Address
      Network IP: Address
      Network mask (or bits): CIDR
      Location: "Display name"
    rules:
      - follow_column: Type
        for_field: Location
      - ingest_only_where:
          Type: Subnet
      - strip_decimal: CIDR

  T2:
    name: DC2 EfficientIP
    file_pattern: dc2-effip-*.csv
    mappings:
      Discovery Range:
        - prefix: dc2_
        - column: Start
      Network IP: Start
      Network mask (or bits): Prefix
      Location: "Class param: 14"

  T3:
    name: DC3 SolarWinds
    file_pattern: dc3-dc3solwind-*.xlsx
    mappings:
      Discovery Range:
        - prefix: dc3_
        - column: Address
      Network IP: Address
      Network mask (or bits): CIDR
      Location:
        - column: Location
        - column: Comments
        - join: " "
    rules:
      - ignore_row_where:
          CIDR:
            - 0
            - 1
            - ""

  T4:
    name: DC4 Infoblox
    file_pattern: dc4-infoblox-*.csv
    mappings:
      Discovery Range:
        - prefix: dc4_
        - column: address*
      Network IP: address*
      Network mask (or bits):
        - column: netmask*
        - function: to_cidr
      Location:
        - column: Site
        - column: Zone
        - column: Space
        - join: " "
    rules:
      - convert_netmask_to_cidr: netmask*